logging:                               
  level: "DEBUG"                      
  log_to_file: false                    
  log_file_dir: "/root/workspace/agent-rm/log"  
  log_file_name: "default.log"        

backend:                                
  model_path: ""                        
  dtype: "auto"                         
  sampling:                             
    temperature: 0.6                      
    max_tokens: 8192                    
    top_p: 1.0                          
    top_k: 20                           
    repetition_penalty: 1.0
  vllm:                                
    gpu_memory_utilization: 0.55         
    tensor_parallel_size: 2
    stop_tokens:
      - "</answer>"
      - "</python>"
      - "</next>"
    use_tqdm: false
  openai:
    api_key: ""
    url: "" 
    max_retries: 3 
    max_concurrency: 3
  rm:
    device: "cuda"
    padding_side: "right"
    apply_sigmoid: true
    head_type: "regression"
    positive_class_index: 0
    clip_range:
      - 0
      - 1.0
    batch_size: null
  hf:
    device: 0
    torch_dtype: "auto"